apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: demos/demo2
    repoURL: https://github.com/irfanazam1/argocd-demo
    targetRevision: HEAD