apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: demos/demo1
    repoURL: https://github.com/irfanazam1/argocd-demo
    targetRevision: HEAD
    helm:
      valueFiles:
      - ../../values/demos/values.yaml
      - ../../values/demos/demo1/values.yaml