apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  namespace: demos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: busybox
        command: ["sleep", "3600000"]