apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - name: demo2
        image: busybox
        command: ["sleep", "3600"]